Pass custom filter functions to add_filter
s-cork/Tabulator pull request #12
Opened 2021-06-14 20:48 UTC by samcarswell

2021-06-15 00:39 UTC, s-cork requested changes

2021-06-15 00:39 UTC, s-cork commented on client_code/Tabulator/__init__.py
> +            filter_func = field
Can we add the default args to type and value so that the type and value aren't required for a custom filter.

2021-06-23 09:51 UTC, s-cork commented
@samcarswell ping

2021-07-17 03:33 UTC, samcarswell commented
Hi @s-cork , sorry I didn't see this previously. I've defaulted `type` and `value`. Let me know if anything else needs to change.

2021-07-17 03:42 UTC, merged